import './globals.css';
import "tw-elements/dist/css/tw-elements.min.css";
import { Inter } from 'next/font/google';

import { Providers } from '@/providers/Providers';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <Suspense fallback={<div>Loading...</div>}> */}
          {children}
          {/* </Suspense> */}
        </Providers>
      </body>
    </html>
  )
}
